# Docker Compose 生产环境覆盖配置
# 用法：docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
#
# 生产环境架构：
# - 所有容器端口仅绑定 127.0.0.1（不直接暴露到公网）
# - 通过宿主机的系统 Nginx 作为反向代理访问
# - 系统 Nginx 监听 0.0.0.0:80 和 0.0.0.0:443，处理 HTTPS
#
# 使用此配置前，请确保：
# 1. 已在宿主机安装系统 Nginx
# 2. 已配置系统 Nginx 反向代理（参考 docs/deployment/DOCKER.md）
# 3. 已获取并配置 HTTPS 证书

version: '3.8'

services:
  # MySQL - 仅本机访问
  mysql:
    ports:
      - "127.0.0.1:3306:3306"

  # 后端 - 仅本机访问，由系统 Nginx 反代 /api 和 /uploads
  backend:
    ports:
      - "127.0.0.1:8080:8080"

  # 前端 - 仅本机访问，由系统 Nginx 反代 /
  frontend:
    ports:
      - "127.0.0.1:8081:80"
