export default [
    {
        path: "/",
        name: "Home",
        component: () => import("@/modules/portal/views/Home.vue"),
        meta: { title: "首页" },
    },
    {
        path: "/login",
        name: "Login",
        component: () => import("@/modules/portal/views/Login.vue"),
        meta: { title: "登录", guest: true },
    },
    {
        path: "/register",
        name: "Register",
        component: () => import("@/modules/portal/views/Register.vue"),
        meta: { title: "注册", guest: true },
    },
    {
        path: "/post/:id",
        name: "PostDetail",
        component: () => import("@/modules/portal/views/PostDetail.vue"),
        meta: { title: "文章详情" },
    },
    {
        path: "/post/create",
        name: "PostCreate",
        component: () => import("@/modules/portal/views/PostEdit.vue"),
        meta: { title: "创建文章", requiresAuth: true },
    },
    {
        path: "/post/:id/edit",
        name: "PostEdit",
        component: () => import("@/modules/portal/views/PostEdit.vue"),
        meta: { title: "编辑文章", requiresAuth: true },
    },
    {
        path: "/profile",
        name: "Profile",
        component: () => import("@/modules/portal/views/Profile.vue"),
        meta: { title: "个人中心", requiresAuth: true },
    },
    {
        path: "/profile/edit",
        name: "ProfileEdit",
        component: () => import("@/modules/portal/views/ProfileEdit.vue"),
        meta: { title: "编辑个人资料", requiresAuth: true },
    },
    {
        path: "/my-comments",
        name: "MyComments",
        component: () => import("@/modules/portal/views/MyComments.vue"),
        meta: { title: "我的评论", requiresAuth: true },
    },
    {
        path: "/user/:username",
        name: "UserProfile",
        component: () => import("@/modules/portal/views/UserProfile.vue"),
        meta: { title: "用户主页" },
    },
    {
        path: "/comment/:id/edit",
        name: "CommentEdit",
        component: () => import("@/modules/portal/views/CommentEdit.vue"),
        meta: { title: "编辑评论", requiresAuth: true },
    },
    {
        path: "/comment/:id/reply",
        name: "ReplyCreate",
        component: () => import("@/modules/portal/views/ReplyCreate.vue"),
        meta: { title: "写回复", requiresAuth: true },
    },
    {
        path: "/tags/:tagName",
        name: "TagPosts",
        component: () => import("@/modules/portal/views/TagPosts.vue"),
        meta: { title: "标签文章" },
    },
    {
        path: "/search",
        name: "Search",
        component: () => import("@/modules/portal/views/Search.vue"),
        meta: { title: "搜索结果" },
    },
    {
        path: "/user/:userId/follow/:type",
        name: "FollowList",
        component: () => import("@/modules/portal/views/FollowList.vue"),
        meta: { title: "关注列表" },
    },
    {
        path: "/settings",
        name: "Settings",
        component: () => import("@/modules/portal/views/Settings.vue"),
        meta: { title: "设置", requiresAuth: true },
    },
    {
        path: "/settings/visibility",
        name: "VisibilitySettings",
        component: () => import("@/modules/portal/views/VisibilitySettings.vue"),
        meta: { title: "隐私设置", requiresAuth: true },
    },
    {
        path: "/messages",
        name: "Messages",
        component: () => import("@/modules/portal/views/Messages.vue"),
        meta: { title: "私信", requiresAuth: true },
    },
    {
        path: "/notifications",
        name: "Notifications",
        component: () => import("@/modules/portal/views/Notifications.vue"),
        meta: { title: "通知", requiresAuth: true },
    },
];
